export const SEARCH_WEATHER_INIT = 'SEARCH_WEATHER_INIT';
export const SEARCH_WEATHER_SUCCESS = 'SEARCH_WEATHER_SUCCESS';
export const SEARCH_WEATHER_FAIL = 'SEARCH_WEATHER_FAIL';

export const ACTIVE_WEATHER = 'ACTIVE_WEATHER';
export const REMOVE_WEATHER = 'REMOVE_WEATHER';

export const SEARCH_FORECAST_INIT = 'SEARCH_FORECAST_INIT';
export const SEARCH_FORECAST_SUCCESS = 'SEARCH_FORECAST_SUCCESS';
export const SEARCH_FORECAST_FAIL = 'SEARCH_FORECAST_FAIL';

export const CLEAR_FORECAST = 'CLEAR_FORECAST';
